mode: "statefulset"

presets:
  kubernetesAttributes:
    enabled: true

config:
  processors:
    k8sattributes:
      extract:
        metadata:
          - "k8s.pod.name"
          - "k8s.pod.start_time"
          - "k8s.pod.uid"
          - "k8s.namespace.name"
          - "k8s.deployment.name"
          - "k8s.replicaset.name"
          - "k8s.replicaset.uid"
          - "k8s.statefulset.name"
          - "k8s.statefulset.uid"
          - "k8s.daemonset.name"
          - "k8s.daemonset.uid"
          - "k8s.cronjob.name"
          - "k8s.job.name"
          - "k8s.job.uid"
          - "k8s.node.name"
          - "container.id"
          - "container.image.name"
          - "container.image.tag"
        annotations:
        - tag_name: "k8s.annotations.workload"
          key: "workload"
          from: pod
        labels:
        - tag_name: "k8s.labels.app"
          key: "app"
          from: pod     
  exporters:
    logging: {}
    file/trace:
      path: /tmp/trace.json
    file/metric:
      path: /tmp/metric.json
    file/log:
      path: /tmp/log.json
  service:
    pipelines:
      traces:
        exporters:
          - file/trace
      metrics:
        exporters:
          - file/metric
      logs:
        exporters:
          - file/log
      
          
image:
  repository: otel/opentelemetry-collector-contrib-dev
  tag: "latest"

command:
  name: otelcontribcol

extraVolumes:
- name: filevolume
  emptyDir: {}
extraVolumeMounts: 
- mountPath: /tmp
  name: filevolume

extraContainers: 
- name: filecp
  image: busybox
  command: ["sh", "-c", "sleep 36000"]   
  volumeMounts:
  - name: filevolume
    mountPath: /tmp
