mode: "statefulset"

presets:
  kubernetesAttributes:
    enabled: true

config:
  exporters:
    logging: {}
    file/trace:
      path: /tmp/trace.json
  service:
    pipelines:
      traces:
        exporters:
          - file/trace

image:
  repository: otel/opentelemetry-collector-contrib-dev
  tag: "latest"

command:
  name: otelcontribcol

extraVolumes:
- name: filevolume
  emptyDir: {}
extraVolumeMounts: 
- mountPath: /tmp
  name: filevolume

extraContainers: 
- name: filecp
  image: busybox
  command: ["sh", "-c", "sleep 36000"]   
  volumeMounts:
  - name: filevolume
    mountPath: /tmp
