apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: telemetrygen-DATA_TYPE-statefulset
  namespace: default
spec:
  serviceName: telemetrygen-DATA_TYPE-statefulset
  replicas: 1
  selector:
    matchLabels:
      app: telemetrygen-DATA_TYPE-statefulset
  template:
    metadata:
    metadata:
      annotations:
        workload: statefulset
      labels:
        app: telemetrygen-DATA_TYPE-statefulset
    spec:
      containers:
      - command:
        - /telemetrygen
        - DATA_TYPE
        - --otlp-insecure
        - --otlp-endpoint=test-opentelemetry-collector:4317
        - --duration=36000s
        - --rate=1
        - --otlp-attributes=service.name="test-statefulset"
        - --otlp-attributes=k8s.container.name="telemetrygen"
        - --otlp-attributes=k8s.container.restart_count="0"
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        imagePullPolicy: IfNotPresent
        name: telemetrygen
        resources: {}
        securityContext: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30