apiVersion: batch/v1
kind: Job
metadata:
  name: test-telemetrygen
  namespace: default
spec:
  template:
    metadata:
      labels:
        component: test-telemetrygen
    spec:
      containers:
      - command:
        - /telemetrygen
        - traces
        - --otlp-insecure
        - --otlp-endpoint=test-opentelemetry-collector:4317
        - --duration=5s
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        imagePullPolicy: IfNotPresent
        name: telemetrygen
        resources: {}
        securityContext: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
