apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: test-telemetrygen-daemonset
spec:
  selector:
    matchLabels:
      app: test-telemetrygen-daemonset
  template:
    metadata:
      annotations:
        workload: daemonset
      labels:
        app: test-telemetrygen-daemonset
    spec:
      containers:
      - command:
        - /telemetrygen
        - traces
        - --otlp-insecure
        - --otlp-endpoint=test-opentelemetry-collector:4317
        - --service=test-daemonset
        - --duration=36000s
        - --rate=1
        - --otlp-attributes=k8s.container.name="telemetrygen"
        - --otlp-attributes=k8s.container.restart_count="0"
        image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
        imagePullPolicy: IfNotPresent
        name: telemetrygen
        resources: {}
        securityContext: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30